"""
CLAW-inspired file editor using exact string matching instead of line numbers.

This module provides a robust, simple way to edit files without line number drift issues.
Key principle: Exact string matching (like CLAW) instead of line-based operations.

Based on: references/claw-code-main/rust/crates/runtime/src/file_ops.rs
"""

import os
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class EditFileOutput:
    """Output structure matching CLAW's EditFileOutput."""
    file_path: str
    old_string: str
    new_string: str
    original_file: str
    structured_patch: List[str]  # Lines with +/- prefix
    user_modified: bool = False
    replace_all: bool = False


def make_patch(original: str, updated: str) -> List[str]:
    """
    Create a structured patch representation (CLAW style).
    
    Returns list of lines, each prefixed with - (removed) or + (added).
    This is for visualization/validation, not application.
    
    Args:
        original: Original file content
        updated: Updated file content
    
    Returns:
        List of patch lines with +/- prefix
    """
    lines = []
    
    # Add removed lines
    for line in original.splitlines():
        lines.append(f"-{line}")
    
    # Add added lines
    for line in updated.splitlines():
        lines.append(f"+{line}")
    
    return lines


def edit_file(
    file_path: str,
    old_string: str,
    new_string: str,
    replace_all: bool = False,
) -> EditFileOutput:
    """
    Edit a file using exact string matching (CLAW-inspired method).
    
    This approach COMPLETELY AVOIDS line number issues by:
    1. Matching exact old_string in file
    2. Replacing with exact new_string
    3. No line number calculations needed
    4. Decorators/braces handled automatically (must match exactly)
    
    Why this works:
    - Old way: replace_lines(55-77) → old_string is guessed from context
    - New way: edit_file(old_string=exact_match) → context is explicit
    
    Result: No duplicate decorators, no extra braces, no off-by-one errors.
    
    Args:
        file_path: Path to file (repo-relative or absolute)
        old_string: EXACT string to find and replace (including decorators, full lines)
        new_string: EXACT string to replace it with (including decorators, full lines)
        replace_all: If False (default), replace only first occurrence.
                    If True, replace all occurrences.
    
    Returns:
        EditFileOutput with:
        - file_path: Absolute path to edited file
        - old_string: What was searched for
        - new_string: What was inserted
        - original_file: Full original content (for verification)
        - structured_patch: Diff representation with +/- prefixes
        - user_modified: False (generated by tool, not user)
        - replace_all: Parameter passed in
    
    Raises:
        ValueError: If:
        - File not found
        - old_string not found in file
        - old_string and new_string are identical
        - Write operation fails
    
    Examples:
        # Fix elasticsearch duplicate @Inject:
        old_str = '''@Inject
    public TransportGetAllocationStatsAction(
        TransportService transportService,
        ...
    ) {
        super(...);
        // OLD CONSTRUCTOR
    }'''
        
        new_str = '''@Inject
    public TransportGetAllocationStatsAction(
        TransportService transportService,
        ...
    ) {
        super(...);
        // NEW CONSTRUCTOR IMPLEMENTATION
    }'''
        
        result = edit_file(
            'server/src/.../TransportGetAllocationStatsAction.java',
            old_str,
            new_str
        )
        # ✅ Result: No duplicate @Inject because exact match includes decorator
    """
    
    # Resolve path
    if not os.path.isabs(file_path):
        file_path = os.path.abspath(file_path)
    
    # Read original file
    try:
        with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
            original_file = f.read()
    except FileNotFoundError as e:
        raise ValueError(f"File not found: {file_path}") from e
    except Exception as e:
        raise ValueError(f"Failed to read file {file_path}: {e}") from e
    
    # VALIDATION FIRST (CLAW pattern, not mutate-first)
    if old_string == new_string:
        raise ValueError(
            "old_string and new_string must differ. "
            "There is nothing to change."
        )
    
    if old_string not in original_file:
        # Provide helpful error with context
        context_start = max(0, original_file.find("Inject") - 50)
        context_end = min(len(original_file), context_start + 200)
        context_preview = original_file[context_start:context_end]
        
        raise ValueError(
            f"old_string not found in file {file_path}\n"
            f"\n"
            f"Searched for (first 150 chars):\n"
            f"{old_string[:150]}\n"
            f"...\n"
            f"\n"
            f"File size: {len(original_file)} bytes, "
            f"{len(original_file.splitlines())} lines\n"
            f"\n"
            f"Context preview:\n"
            f"{context_preview}"
        )
    
    # Count occurrences for debugging
    occurrence_count = original_file.count(old_string)
    if occurrence_count > 1 and not replace_all:
        # Warn if multiple matches
        pass  # OK, we'll replace first only
    
    # THEN mutate (after all validations)
    if replace_all:
        updated = original_file.replace(old_string, new_string)
    else:
        # Replace only first occurrence
        updated = original_file.replace(old_string, new_string, 1)
    
    # Write back to file
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(updated)
    except Exception as e:
        raise ValueError(f"Failed to write file {file_path}: {e}") from e
    
    # Build and return output (CLAW style)
    return EditFileOutput(
        file_path=file_path,
        old_string=old_string,
        new_string=new_string,
        original_file=original_file,
        structured_patch=make_patch(original_file, updated),
        user_modified=False,
        replace_all=replace_all,
    )


def verify_edit_output(output: EditFileOutput) -> str:
    """
    Verify that an edit operation produced valid results.
    
    This is called AFTER edit_file() to double-check the filesystem state.
    
    Args:
        output: EditFileOutput from edit_file()
    
    Returns:
        "ALL_GOOD" if valid, or error message if invalid
    """
    
    # Check that strings differ
    if output.old_string == output.new_string:
        return "ERROR: old_string and new_string are identical"
    
    # Read the file back from disk
    try:
        with open(output.file_path, 'r', encoding='utf-8', errors='replace') as f:
            current = f.read()
    except Exception as e:
        return f"ERROR: Failed to read file after edit: {e}"
    
    # Verify new_string is in file
    if output.new_string not in current:
        return (
            f"ERROR: new_string not found in file after edit. "
            f"This indicates the replacement didn't take effect. "
            f"First 100 chars of new_string: {output.new_string[:100]}"
        )
    
    # Verify old_string is gone (if replace_all)
    if output.replace_all and output.old_string in current:
        count = current.count(output.old_string)
        return (
            f"ERROR: old_string still found in file after replace_all. "
            f"Found {count} occurrences. "
            f"This indicates replace_all didn't work."
        )
    
    # Check structured patch is reasonable
    if not output.structured_patch:
        return "ERROR: No patch lines generated (empty structured_patch)"
    
    return "ALL_GOOD"


def get_exact_method_for_editing(
    file_content: str,
    method_signature_start: str,
    context_lines_before: int = 2,
) -> Optional[str]:
    """
    Helper: Extract an exact method string for use with edit_file().
    
    Finds a method in file_content and returns the exact text needed for old_string.
    
    Args:
        file_content: Full file content
        method_signature_start: Something like "public TransportGetAllocationStatsAction("
        context_lines_before: How many lines before method to include (for decorators)
    
    Returns:
        Exact method text (with decorators) suitable for old_string, or None if not found
    """
    
    lines = file_content.splitlines(keepends=True)
    
    # Find the method signature
    method_line_idx = None
    for i, line in enumerate(lines):
        if method_signature_start in line:
            method_line_idx = i
            break
    
    if method_line_idx is None:
        return None
    
    # Go back to find decorators (@Inject, etc.)
    start_idx = max(0, method_line_idx - context_lines_before)
    
    # Find opening brace
    brace_depth = 0
    end_idx = method_line_idx
    for i in range(method_line_idx, len(lines)):
        brace_depth += lines[i].count('{') - lines[i].count('}')
        if brace_depth > 0 and i > method_line_idx:
            # Still in method body
            if brace_depth == 0:
                # Found matching closing brace
                end_idx = i
                break
    
    # Extract exact text
    exact_text = ''.join(lines[start_idx:end_idx + 1])
    return exact_text.rstrip()  # Remove trailing whitespace


if __name__ == "__main__":
    # Simple test
    print("CLAW File Editor Module")
    print("=" * 50)
    print("Ready to use in: agents-backend/src/agents/hunk_generator_tools.py")
    print()
    print("Key pattern:")
    print("  from claw_file_editor import edit_file")
    print("  result = edit_file(path, old_string, new_string)")
    print()
    print("This avoids line drift because:")
    print("  ✓ No line number calculations")
    print("  ✓ Exact string matching")
    print("  ✓ Decorators automatic (part of string match)")
    print("  ✓ Braces automatic (must balance in string match)")
